AWSTemplateFormatVersion: '2010-09-09'
Description: "Media Insights Engine - Workflow to run comprehend"

Parameters:
  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the Media Insights custom resource that handles creating operations, stages and workflows"
  # FIXME - this doesn't work well with nesting - just pass in the layer resource
  # MediaInsightsWorkflowStack:
    # Description: "Name of the base media insights workflow stack"
    # Type: String
  OperatorLibraryStack:
    Description: "Name of the operator library stack"
    Type: String

Resources:

  # Stages

  ParallelComprehendStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "ParallelComprehendStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ComprehendPhrases"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ComprehendEntities"


  # Workflows

  ParallelComprehendWorkflow:
    DependsOn:
      - ParallelComprehendStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: "ParallelComprehendWorkflow"
      Stages: !Sub
        - |-
          {
            "${parallelComprehend}":
            {
              "End": true
            }
          }
        - {
          parallelComprehend: !GetAtt ParallelComprehendStage.Name
        }
      StartAt: !GetAtt ParallelComprehendStage.Name