AWSTemplateFormatVersion: '2010-09-09'
Description: "Media Insights Engine - Workflow to run Rekognition"

Parameters:
  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the Media Insights custom resource that handles creating operations, stages and workflows"
  # FIXME - this doesn't work well with nesting - just pass in the layer resource
  # MediaInsightsWorkflowStack:
    # Description: "Name of the base media insights workflow stack"
    # Type: String
  OperatorLibraryStack:
    Description: "Name of the operator library stack"
    Type: String

Resources:

  # Stages

  parallelRekognitionStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "parallelRekognitionStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:CelebRecognition"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ContentModeration"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceDetection"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceSearch"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:LabelDetection"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:PersonTracking"


  # Face search operation requires a custom input without any pre-existing default so it has a prerequiste step to create a collection
  # to search against.  This workflow should run without any pre-requisite step.
  RekognitionVideoNoFaceSearchStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "RekognitionVideoNoFaceSearchStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:LabelDetection"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:PersonTracking"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:CelebRecognition"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ContentModeration"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceDetection"

  RekognitionStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "RekognitionStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:CelebRecognitionImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ContentModerationImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceDetectionImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceSearchImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:LabelDetectionImage"

  # Face search operation requires a custom input without any pre-existing default so it has a prerequiste step to create a collection
  # to search against.  This workflow should run without any pre-requisite step.
  RekognitionImageNoFaceSearchStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "RekognitionImageNoFaceSearchStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:CelebRecognitionImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ContentModerationImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceDetectionImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:LabelDetectionImage"

  # Workflows

# Do we need a sequential rekognition workflow?

#  SequentialRekognitionWorkflow:
#    DependsOn:
#    Type: Custom::CustomResource
#    Properties:
#      ServiceToken: !Ref WorkflowCustomResourceArn
#      ResourceType: "Workflow"
#      Name: "SequentialRekognitionWorkflow"
#      StartAt: !GetAtt celebrityRecognitionOperation.StageName
#      Stages: !Sub
#        - |-
#          {
#            "${celebrityRecognitionStage}":{
#              "Next": "${contentModerationStage}"
#              },
#            "${contentModerationStage}":{
#              "Next": "${faceDetectionStage}"
#              },
#            "${faceDetectionStage}":{
#              "Next": "${faceSearchStage}"
#              },
#            "${faceSearchStage}":{
#              "Next": "${labelDetectionStage}"
#              },
#            "${labelDetectionStage}":{
#              "Next": "${personTrackingStage}"
#              },
#            "${personTrackingStage}":{
#              "End": true
#              }
#          }
#        - {
#          celebrityRecognitionStage: !GetAtt celebrityRecognitionOperation.StageName,
#          contentModerationStage: !GetAtt contentModerationOperation.StageName,
#          faceDetectionStage: !GetAtt faceDetectionOperation.StageName,
#          faceSearchStage: !GetAtt faceSearchOperation.StageName,
#          labelDetectionStage: !GetAtt labelDetectionOperation.StageName,
#          personTrackingStage: !GetAtt personTrackingOperation.StageName
#        }


  ParallelRekognitionWorkflow:
    DependsOn:
      - parallelRekognitionStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: "ParallelRekognitionWorkflow"
      Stages: !Sub
        - |-
          {
            "${rekognitionSuite}":
            {
              "End": true
            }
          }
        - {
          rekognitionSuite: !GetAtt parallelRekognitionStage.Name
        }
      StartAt: !GetAtt parallelRekognitionStage.Name



  ImageWorkflow:
    DependsOn:
      - RekognitionStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: "ImageWorkflow"
      Stages: !Sub
        - |-
          {
            "${rekognitionSuite}":
            {
              "End": true
            }
          }
        - {
          rekognitionSuite: !GetAtt RekognitionStage.Name
        }
      StartAt: !GetAtt RekognitionStage.Name

  RekognitionVideoWorkflow:
    DependsOn:
      - RekognitionVideoNoFaceSearchStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: "RekognitionVideoWorkflow"
      Stages: !Sub
        - |-
          {
            "${rekognitionSuite}":
            {
              "End": true
            }
          }
        - {
          rekognitionSuite: !GetAtt RekognitionVideoNoFaceSearchStage.Name
        }
      StartAt: !GetAtt RekognitionVideoNoFaceSearchStage.Name

  RekognitionImageWorkflow:
    DependsOn:
      - RekognitionImageNoFaceSearchStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: "RekognitionImageWorkflow"
      Stages: !Sub
        - |-
          {
            "${rekognitionSuite}":
            {
              "End": true
            }
          }
        - {
          rekognitionSuite: !GetAtt RekognitionImageNoFaceSearchStage.Name
        }
      StartAt: !GetAtt RekognitionImageNoFaceSearchStage.Name

