AWSTemplateFormatVersion: '2010-09-09'
Description: "Media Insights Engine - Workflow to run Rekognition"

Parameters:
  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the Media Insights custom resource that handles creating operations, stages and workflows"
  # FIXME - this doesn't work well with nesting - just pass in the layer resource
  # MediaInsightsWorkflowStack:
    # Description: "Name of the base media insights workflow stack"
    # Type: String
  OperatorLibraryStack:
    Description: "Name of the operator library stack"
    Type: String
  ShortUUID:
    Type: String
    Description: "A short UUID that is going to be appended to resource names"

Resources:

  # Stages

  ValidationStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "ValidationStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:MediainfoImage"

  parallelRekognitionStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "parallelRekognitionStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:CelebRecognition"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ContentModeration"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceDetection"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceSearch"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:LabelDetection"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:PersonTracking"


  # Face search operation requires a custom input without any pre-existing default so it has a prerequiste step to create a collection
  # to search against.  This workflow should run without any pre-requisite step.
  RekognitionVideoNoFaceSearchStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "RekogVdNoFaceSearchStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:LabelDetection"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:PersonTracking"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:CelebRecognition"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ContentModeration"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceDetection"

  RekognitionStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "RekognitionStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:CelebRecognitionImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ContentModerationImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceDetectionImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceSearchImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:LabelDetectionImage"

  # Face search operation requires a custom input without any pre-existing default so it has a prerequiste step to create a collection
  # to search against.  This workflow should run without any pre-requisite step.
  RekognitionImageNoFaceSearchStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "RekogImNoFaceSearchStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:CelebRecognitionImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ContentModerationImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceDetectionImage"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:LabelDetectionImage"

  # Workflows

  ImageWorkflow:
    DependsOn:
      - ValidationStage
      - RekognitionStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: !Sub "ImageWorkflow-${ShortUUID}"
      StartAt: !GetAtt ValidationStage.Name
      Stages: !Sub
        - |-
          {
            "${ValidationStage}":{
              "Next": "${rekognitionSuite}"
              },
            "${rekognitionSuite}":{
              "End": true
              }
          }
        - {
          ValidationStage: !GetAtt ValidationStage.Name,
          rekognitionSuite: !GetAtt RekognitionStage.Name
        }

  RekognitionVideoWorkflow:
    DependsOn:
      - RekognitionVideoNoFaceSearchStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: !Sub "RekognitionVideoWorkflow-${ShortUUID}"
      Stages: !Sub
        - |-
          {
            "${rekognitionSuite}":
            {
              "End": true
            }
          }
        - {
          rekognitionSuite: !GetAtt RekognitionVideoNoFaceSearchStage.Name
        }
      StartAt: !GetAtt RekognitionVideoNoFaceSearchStage.Name

  RekognitionImageWorkflow:
    DependsOn:
      - RekognitionImageNoFaceSearchStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: !Sub "RekognitionImageWorkflow-${ ShortUUID}"
      Stages: !Sub
        - |-
          {
            "${rekognitionSuite}":
            {
              "End": true
            }
          }
        - {
          rekognitionSuite: !GetAtt RekognitionImageNoFaceSearchStage.Name
        }
      StartAt: !GetAtt RekognitionImageNoFaceSearchStage.Name
